FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN npm install -g nodemon

COPY tsconfig.json ./
COPY . .

EXPOSE 3000

CMD ["nodemon", "--watch", ".", "--ext", "ts", "--exec", "ts-node", "app.local.ts"]
